version: '3'
services:
  # Your Go application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Set environment variables from your .env file
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DIALECT: ${DB_DIALECT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: ["./main"]

    entrypoint:
      - sh
      - -c
      - >
        go run cmd/migrate/migrate.go &
        ./main 

  # PostgreSQL database service
  db:
    image: postgres:15.4
    container_name: invitations-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # Add any additional services you need here (e.g., Redis, etc.)

# Define your network settings if necessary

